# Generated by Django 3.2.3 on 2021-08-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='student_profile/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
