# Generated by Django 3.2.3 on 2021-10-12 10:16

from django.db import migrations, models
import genericview.models


class Migration(migrations.Migration):

    dependencies = [
        ('genericview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(validators=[genericview.models.validate]),
        ),
    ]
